### ISSUE TITLE
Any updates on releasing the pre-trained models

### ISSUE THREAD

**Issue by amil-rp-work** [jacobswan1/Video_S3D_Talker#2]
Hey @jacobswan1 
Thanks a ton for open-sourcing your amazing work!!!
I was wondering if you plan to release the pre-trained models soon for inferencing on a single raw video.

**Comment by jacobswan1** [comment]
Hi Amil, thanks for your interest in the project! Right now I'm entirely buried by the ICLR deadline, I'll continue releasing a stronger version of the implementation, NCE features as well as the pre-trained model in a month. 
However for the model released, I think it may still need pre-extracted S3D features as offline input rather than direct inference on single raw videos.  To do direct inference, I think you might want to write a script to:

1) downsample/pre-process and extract S3D features online from the raw videos
2) feed S3D features into the captioning model

**Comment by amil-rp-work** [comment]
Hey @jacobswan1 
Thanks for the update, all the best for ICLR !!!
I will work on the script for the above-mentioned feature extractions.
